### Initialize tensors

In [ ]:
import torch
import numpy as np

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"  # Cuda to run on GPU!


In [ ]:
my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True
)

In [ ]:
my_tensor.nelement()

6

In [ ]:
print(
    f"Information about tensor: {my_tensor}"
)  # Prints data of the tensor, device and grad info
print(
    f"Type of Tensor {my_tensor.dtype}"
)  # Prints dtype of the tensor (torch.float32, etc)
print(
    f"Device Tensor is on {my_tensor.device}"
)  # Prints cpu/cuda (followed by gpu number)
print(f"Shape of tensor {my_tensor.shape}")  # Prints shape, in this case 2x3
print(f"Requires gradient: {my_tensor.requires_grad}")  # Prints true/false

Information about tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
Type of Tensor torch.float32
Device Tensor is on cuda:0
Shape of tensor torch.Size([2, 3])
Requires gradient: True


In [ ]:
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
x

tensor([[-2.8346e-33,  4.4840e-41,  6.9264e-30],
        [ 0.0000e+00,  7.8290e-30,  0.0000e+00],
        [ 2.4682e-33,  0.0000e+00,  0.0000e+00]])

In [ ]:
x = torch.rand((2, 3))  # Tensor of shape 3x3 with values of 0
x

tensor([[0.6787, 0.9374, 0.4770],
        [0.8376, 0.5313, 0.7947]])

In [ ]:
torch.zeros_like(x)  # Tensor of shape 3x3 with values of 0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x = torch.rand(
    (3, 3)
)  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)

In [ ]:
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.triu(x, diagonal=1)

tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 0.]])

In [ ]:
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
x = torch.arange(
    start=0, end=5, step=1
)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(11)
x

tensor([0, 1, 2, 3, 4])

In [ ]:
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [ ]:
x = torch.empty(size=(1, 5)).normal_(
    mean=0, std=1
)  # Normally distributed with mean=0, std=1
x

tensor([[-0.4647,  0.2569, -0.4933, -0.4327,  0.8193]])

In [ ]:
x = torch.empty(size=(1, 5)).uniform_(
    0, 1
)  # Values from a uniform distribution low=0, high=1

In [ ]:
y=torch.rand(3,3)
print(y)
print("\n")
x = torch.diag(y)  # Diagonal matrix of shape 3x3
x

tensor([[0.4906, 0.5553, 0.2622],
        [0.1623, 0.8256, 0.8871],
        [0.1452, 0.4542, 0.8798]])




tensor([0.4906, 0.8256, 0.8798])

In [ ]:
tensor = torch.arange(4)  # [0, 1, 2, 3] Initialized as int64 by default
print(f"Converted Boolean: {tensor.bool()}")  # Converted to Boolean: 1 if nonzero
print(f"Converted int16 {tensor.short()}")  # Converted to int16
print(
    f"Converted int64 {tensor.long()}"
)  # Converted to int64 (This one is very important, used super often)
print(f"Converted float16 {tensor.half()}")  # Converted to float16
print(
    f"Converted float32 {tensor.float()}"
)  # Converted to float32 (This one is very important, used super often)
print(f"Converted float64 {tensor.double()}")  # Converted to float64


Converted Boolean: tensor([False,  True,  True,  True])
Converted int16 tensor([0, 1, 2, 3], dtype=torch.int16)
Converted int64 tensor([0, 1, 2, 3])
Converted float16 tensor([0., 1., 2., 3.], dtype=torch.float16)
Converted float32 tensor([0., 1., 2., 3.])
Converted float64 tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
np_array_again = (
    tensor.numpy()
)  # np_array_again will be same as np_array (perhaps with numerical round offs)

### Tensor Math & Comparison Operations  

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7, 8])

In [ ]:
z2 = torch.add(x, y)
z2

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [ ]:
torch.subtract(x, y)

tensor([-8, -6, -4])

In [ ]:
x + y

tensor([10, 10, 10])

In [ ]:
x - y

tensor([-8, -6, -4])

In [ ]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [ ]:
# -- Inplace Operations --
t = torch.zeros(3)
print(t)

t.add_(x)  # Whenever we have operation followed by _ it will mutate the tensor in place
t += x  # Also inplace
print(t)

tensor([0., 0., 0.])
tensor([2., 4., 6.])


In [ ]:
# -- Exponentiation --
z = x.pow(2)  # z = [1, 4, 9]
z = x**2  # z = [1, 4, 9]

In [ ]:
z = x > 0  # Returns [True, True, True]
z = x < 0  # Returns [False, False, False]

In [ ]:
x1 = torch.rand((2, 5))
print(x1)
print("\n")

x2 = torch.rand((5, 3))
print(x2)
print("\n")

x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
print(x3)

tensor([[0.2854, 0.0284, 0.7142, 0.5575, 0.4672],
        [0.6759, 0.5752, 0.1610, 0.2334, 0.3734]])


tensor([[0.2663, 0.8196, 0.1117],
        [0.3621, 0.8272, 0.4406],
        [0.4303, 0.9158, 0.8760],
        [0.5390, 0.5782, 0.1401],
        [0.0993, 0.7633, 0.8131]])


tensor([[0.7404, 1.5904, 1.1280],
        [0.6204, 1.5972, 0.8063]])


In [ ]:
x1@x2

tensor([[0.7404, 1.5904, 1.1280],
        [0.6204, 1.5972, 0.8063]])

In [ ]:
x1.mm(x2)

tensor([[0.7404, 1.5904, 1.1280],
        [0.6204, 1.5972, 0.8063]])

In [ ]:
matrix_exp = torch.rand(5, 5)
print(matrix_exp)
print("\n")
print(
    matrix_exp.matrix_power(3)
)  # is same as matrix_exp (mm) matrix_exp (mm) matrix_exp

tensor([[0.1140, 0.6547, 0.5395, 0.7345, 0.2381],
        [0.3197, 0.4620, 0.2840, 0.9061, 0.8724],
        [0.9396, 0.9269, 0.5032, 0.9023, 0.7048],
        [0.3060, 0.9004, 0.1595, 0.2616, 0.3616],
        [0.0448, 0.9939, 0.4711, 0.3938, 0.1026]])


tensor([[1.8809, 4.7113, 2.2298, 3.8711, 2.9602],
        [2.2915, 4.9572, 2.3450, 4.4360, 3.6071],
        [3.3542, 7.5848, 3.4909, 6.3179, 5.0620],
        [1.6457, 4.0135, 1.7935, 3.0920, 2.4414],
        [1.6789, 4.5347, 2.0836, 3.4262, 2.5617]])


In [ ]:
matrix_exp@matrix_exp@matrix_exp

tensor([[1.8809, 4.7113, 2.2298, 3.8711, 2.9602],
        [2.2915, 4.9572, 2.3450, 4.4360, 3.6071],
        [3.3542, 7.5848, 3.4909, 6.3179, 5.0620],
        [1.6457, 4.0135, 1.7935, 3.0920, 2.4414],
        [1.6789, 4.5347, 2.0836, 3.4262, 2.5617]])

In [ ]:
matrix_exp**3

tensor([[1.4805e-03, 2.8058e-01, 1.5706e-01, 3.9631e-01, 1.3506e-02],
        [3.2678e-02, 9.8588e-02, 2.2898e-02, 7.4404e-01, 6.6408e-01],
        [8.2950e-01, 7.9637e-01, 1.2741e-01, 7.3460e-01, 3.5003e-01],
        [2.8657e-02, 7.3008e-01, 4.0539e-03, 1.7909e-02, 4.7273e-02],
        [8.9813e-05, 9.8170e-01, 1.0453e-01, 6.1059e-02, 1.0805e-03]])

In [ ]:
matrix_exp.pow(3)

tensor([[1.4805e-03, 2.8058e-01, 1.5706e-01, 3.9631e-01, 1.3506e-02],
        [3.2678e-02, 9.8588e-02, 2.2898e-02, 7.4404e-01, 6.6408e-01],
        [8.2950e-01, 7.9637e-01, 1.2741e-01, 7.3460e-01, 3.5003e-01],
        [2.8657e-02, 7.3008e-01, 4.0539e-03, 1.7909e-02, 4.7273e-02],
        [8.9813e-05, 9.8170e-01, 1.0453e-01, 6.1059e-02, 1.0805e-03]])

In [ ]:
matrix_exp*matrix_exp*matrix_exp

tensor([[1.4805e-03, 2.8058e-01, 1.5706e-01, 3.9631e-01, 1.3506e-02],
        [3.2678e-02, 9.8588e-02, 2.2898e-02, 7.4404e-01, 6.6408e-01],
        [8.2950e-01, 7.9637e-01, 1.2741e-01, 7.3460e-01, 3.5003e-01],
        [2.8657e-02, 7.3008e-01, 4.0539e-03, 1.7909e-02, 4.7273e-02],
        [8.9813e-05, 9.8170e-01, 1.0453e-01, 6.1059e-02, 1.0805e-03]])

In [ ]:
t = torch.ones((3,3))
print(t)
torch.exp(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183],
        [2.7183, 2.7183, 2.7183]])

In [ ]:
import math
math.e**0.1329

1.1421357790421207

In [ ]:
z = torch.dot(x, y)
z

RuntimeError: inconsistent tensor size, expected tensor [3] and src [4] to have the same number of elements, but got 3 and 4 elements respectively

In [ ]:
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # Will be shape: (b x n x p)

In [ ]:
print(tensor1)
print("\n")
print(tensor2)
print("\n")
print(out_bmm.shape)


tensor([[[9.8038e-01, 9.8813e-01, 3.5680e-01,  ..., 9.8985e-01,
          8.5053e-01, 2.1648e-01],
         [9.7417e-01, 9.3869e-01, 9.5796e-01,  ..., 4.4404e-01,
          6.0848e-01, 1.8526e-01],
         [5.4595e-01, 3.2652e-01, 1.0672e-02,  ..., 9.4811e-01,
          7.4017e-01, 6.3535e-01],
         ...,
         [4.1733e-01, 2.6474e-01, 4.8846e-01,  ..., 2.9338e-01,
          6.6010e-01, 7.4619e-01],
         [5.4607e-01, 2.5753e-01, 1.3760e-01,  ..., 8.2780e-01,
          5.6017e-02, 4.2046e-01],
         [6.2968e-01, 2.4155e-01, 8.9073e-01,  ..., 4.8414e-01,
          5.9949e-01, 3.7681e-01]],

        [[9.0042e-01, 4.8265e-01, 3.7425e-01,  ..., 8.4686e-01,
          4.1728e-01, 3.8691e-01],
         [9.5170e-01, 8.8676e-01, 4.9835e-01,  ..., 4.1511e-01,
          3.9281e-01, 5.5331e-01],
         [7.8889e-01, 6.5299e-01, 8.2030e-01,  ..., 8.7267e-01,
          2.9368e-01, 9.5591e-01],
         ...,
         [5.9980e-01, 9.2602e-01, 8.8614e-02,  ..., 1.2715e-01,
          9.820

In [ ]:
A = torch.tensor([[1, 2], [3, 4], [2, 4]])  # Shape (3,2)
B = torch.tensor([[5, 6], [7, 8], [1, 3]])  # Shape (3,2)

In [ ]:
A

tensor([[1, 2],
        [3, 4],
        [2, 4]])

In [ ]:
B

tensor([[5, 6],
        [7, 8],
        [1, 3]])

In [ ]:
A.shape

torch.Size([3, 2])

In [ ]:
A.unsqueeze(dim=0)

tensor([[[1, 2],
         [3, 4],
         [2, 4]]])

In [ ]:
A.unsqueeze(dim=0).shape

torch.Size([1, 3, 2])

In [ ]:
A = A.unsqueeze(dim=0).expand(4, -1, -1)
A

tensor([[[1, 2],
         [3, 4],
         [2, 4]],

        [[1, 2],
         [3, 4],
         [2, 4]],

        [[1, 2],
         [3, 4],
         [2, 4]],

        [[1, 2],
         [3, 4],
         [2, 4]]])

In [ ]:
B = B.unsqueeze(dim=0).expand(4, -1, -1)

In [ ]:
A.shape

torch.Size([4, 3, 2])

In [ ]:
B.shape

torch.Size([4, 3, 2])

In [ ]:
B = B.view(-1, B.shape[2], B.shape[1])

In [ ]:
B

tensor([[[5, 6, 7],
         [8, 1, 3]],

        [[5, 6, 7],
         [8, 1, 3]],

        [[5, 6, 7],
         [8, 1, 3]],

        [[5, 6, 7],
         [8, 1, 3]]])

In [ ]:
B.shape

torch.Size([4, 2, 3])

In [ ]:
torch.bmm(A, B)

tensor([[[21,  8, 13],
         [47, 22, 33],
         [42, 16, 26]],

        [[21,  8, 13],
         [47, 22, 33],
         [42, 16, 26]],

        [[21,  8, 13],
         [47, 22, 33],
         [42, 16, 26]],

        [[21,  8, 13],
         [47, 22, 33],
         [42, 16, 26]]])

In [ ]:
x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))

In [ ]:
x1

tensor([[0.7117, 0.0982, 0.1697, 0.1924, 0.7254],
        [0.7473, 0.9070, 0.3322, 0.9690, 0.9463],
        [0.4787, 0.2123, 0.6844, 0.6257, 0.4487],
        [0.9804, 0.2968, 0.5525, 0.5264, 0.0579],
        [0.6704, 0.5878, 0.7634, 0.4269, 0.9770]])

In [ ]:
x2 = torch.tensor([4])

In [ ]:
x1*x2

tensor([[2.8467, 0.3930, 0.6789, 0.7696, 2.9016],
        [2.9894, 3.6278, 1.3286, 3.8761, 3.7851],
        [1.9147, 0.8491, 2.7374, 2.5028, 1.7947],
        [3.9215, 1.1872, 2.2100, 2.1056, 0.2317],
        [2.6814, 2.3513, 3.0537, 1.7076, 3.9080]])

In [ ]:
x2-x1

tensor([[0.7745, 1.0000, 0.0997, 0.9664, 0.3540],
        [0.0680, 0.0609, 0.9555, 0.5576, 0.2219],
        [0.7848, 0.4066, 0.0532, 0.3178, 0.6392],
        [0.8466, 0.9554, 0.3275, 0.5734, 0.0503],
        [0.8498, 0.3397, 0.3341, 0.7390, 0.0931]])

In [ ]:
x2 * x1

tensor([[0.0069, 0.4363, 0.3781, 0.8571, 0.1580],
        [0.7336, 0.8061, 0.2010, 0.9492, 0.1309],
        [0.2600, 0.8864, 0.6046, 0.0462, 0.9662],
        [0.3700, 0.9759, 0.9402, 0.7867, 0.4431],
        [0.0690, 0.8093, 0.9005, 0.8662, 0.8800]])

In [ ]:
43**2

1849

In [ ]:
A

tensor([[1, 2],
        [3, 4],
        [2, 4]])

In [ ]:
sum_A = torch.sum(
    A, dim=0
)
sum_A

tensor([ 6, 10])

In [ ]:
P = torch.tensor([[5, 6, 7],
         [8, 1, 3]])

In [ ]:
P

tensor([[5, 6, 7],
        [8, 1, 3]])

In [ ]:
torch.sum(P, dim=0)

tensor([13,  7, 10])

In [ ]:
torch.sum(P, dim=1)

tensor([18, 12])

In [ ]:
P

tensor([[5, 6, 7],
        [8, 1, 3]])

In [ ]:
values, indices = torch.max(P, dim=0)
values, indices

(tensor([8, 6, 7]), tensor([1, 0, 0]))

In [ ]:
values, indices = torch.max(P, dim=1)
values, indices

(tensor([7, 8]), tensor([2, 0]))

In [ ]:
abs_x = torch.abs(P)
abs_x

tensor([[5, 6, 7],
        [8, 1, 3]])

In [ ]:
P

tensor([[5, 6, 7],
        [8, 1, 3]])

In [ ]:
torch.argmax(P, dim=0)

tensor([1, 0, 0])

In [ ]:
torch.argmax(P, dim=1)

tensor([2, 0])

In [ ]:
z = torch.eq(x, y)  # Element wise comparison, in this case z = [False, False, False]
z


tensor([False, False, False])

In [ ]:
z = torch.eq(A, B)  # Element wise comparison, in this case z = [False, False, False]
z


tensor([[False, False],
        [False, False],
        [False, False]])

In [ ]:
print(x)
z = torch.clamp(x, min=2)
z

tensor([1, 2, 3])


tensor([2, 2, 3])

In [ ]:
x = torch.tensor([1, 0, 6, 5, -1], dtype=torch.bool)
x

tensor([ True, False,  True,  True,  True])

In [ ]:
z = torch.any(x)
z

tensor(True)

In [ ]:
z = torch.all(x)
z

tensor(False)

 ### Tensor Indexing

In [ ]:
batch_size = 10
features = 25

In [ ]:
x = torch.rand((batch_size, features))
print(x.shape)
print("\n")
print(x)

torch.Size([10, 25])


tensor([[0.8890, 0.3289, 0.5066, 0.6957, 0.9740, 0.0547, 0.7570, 0.8483, 0.3536,
         0.0748, 0.8455, 0.0872, 0.9404, 0.0853, 0.2617, 0.8077, 0.4719, 0.1769,
         0.8815, 0.8931, 0.2712, 0.7666, 0.5662, 0.0093, 0.4283],
        [0.6324, 0.3976, 0.7950, 0.6447, 0.1386, 0.3943, 0.8312, 0.7493, 0.4578,
         0.0568, 0.7437, 0.5563, 0.0729, 0.7224, 0.7849, 0.9468, 0.8964, 0.3368,
         0.6046, 0.2137, 0.2928, 0.7093, 0.8768, 0.5370, 0.0264],
        [0.7876, 0.4973, 0.5777, 0.4075, 0.8760, 0.0404, 0.9571, 0.5904, 0.6459,
         0.7446, 0.8985, 0.1651, 0.2629, 0.1886, 0.9340, 0.5604, 0.7390, 0.4169,
         0.2631, 0.3357, 0.0125, 0.1249, 0.4188, 0.2381, 0.4714],
        [0.3988, 0.9701, 0.1867, 0.2142, 0.8626, 0.3822, 0.7283, 0.5628, 0.4387,
         0.9483, 0.3152, 0.5915, 0.7669, 0.4138, 0.4944, 0.6787, 0.7195, 0.0489,
         0.7733, 0.2602, 0.0049, 0.0720, 0.1918, 0.0211, 0.3349],
        [0.7897, 0.8322, 0.6004, 0.2181, 0.6341, 0.8924, 0.4148, 

In [ ]:
x[0].shape

torch.Size([25])

In [ ]:
x[:, 0]

tensor([0.8890, 0.6324, 0.7876, 0.3988, 0.7897, 0.2292, 0.2663, 0.4911, 0.1379,
        0.1910])

In [ ]:
x[2, 0:10]

tensor([0.7876, 0.4973, 0.5777, 0.4075, 0.8760, 0.0404, 0.9571, 0.5904, 0.6459,
        0.7446])

In [ ]:
x[0, 0] = 100

In [ ]:
x

tensor([[1.0000e+02, 3.2888e-01, 5.0660e-01, 6.9571e-01, 9.7395e-01, 5.4713e-02,
         7.5698e-01, 8.4829e-01, 3.5364e-01, 7.4767e-02, 8.4551e-01, 8.7250e-02,
         9.4043e-01, 8.5324e-02, 2.6166e-01, 8.0767e-01, 4.7186e-01, 1.7692e-01,
         8.8149e-01, 8.9308e-01, 2.7124e-01, 7.6658e-01, 5.6623e-01, 9.3103e-03,
         4.2835e-01],
        [6.3242e-01, 3.9759e-01, 7.9498e-01, 6.4473e-01, 1.3865e-01, 3.9429e-01,
         8.3117e-01, 7.4934e-01, 4.5779e-01, 5.6777e-02, 7.4370e-01, 5.5634e-01,
         7.2936e-02, 7.2238e-01, 7.8494e-01, 9.4683e-01, 8.9644e-01, 3.3683e-01,
         6.0456e-01, 2.1369e-01, 2.9277e-01, 7.0927e-01, 8.7680e-01, 5.3697e-01,
         2.6406e-02],
        [7.8761e-01, 4.9727e-01, 5.7767e-01, 4.0747e-01, 8.7605e-01, 4.0386e-02,
         9.5707e-01, 5.9042e-01, 6.4589e-01, 7.4463e-01, 8.9854e-01, 1.6515e-01,
         2.6292e-01, 1.8863e-01, 9.3403e-01, 5.6039e-01, 7.3904e-01, 4.1694e-01,
         2.6314e-01, 3.3572e-01, 1.2550e-02, 1.2490e-01, 4.1879e-

In [ ]:
x = torch.arange(10)
print(x)
print(x[(x < 2) | (x > 8)])  # will be [0, 1, 9]
print(x[x.remainder(2) == 0])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [ ]:
x = torch.arange(10)
print(
    x.numel()
)

10


In [ ]:
A = torch.tensor([[1, 2], [3, 4], [2, 4]])
A.numel()

6

In [ ]:
A.nelement()

6

### Tensor Reshaping